ci: deploy plain index file

diff --git a/.caprover/Dockerfile b/.caprover/Dockerfile
--- a/.caprover/Dockerfile
+++ b/.caprover/Dockerfile
@@ -20,7 +20,8 @@ FROM nginx:stable-alpine as webserver
 RUN rm -rf /etc/nginx/conf.d
 RUN mkdir -p /etc/nginx/conf.d
 COPY ./.caprover/default.conf /etc/nginx/conf.d/
-COPY --from=vite_build /build/.vitepress/dist /usr/share/nginx/html
+# COPY --from=vite_build /build/.vitepress/dist /usr/share/nginx/html
+RUN echo "hellø" >> /usr/share/nginx/html/index.html
 
 # release app
 EXPOSE 80
@@ -30,6 +31,6 @@ CMD ["nginx", "-g", "daemon off;"]
 # ##############################
 # Health check for zero-downtime deploys
 # ##############################
-HEALTHCHECK \
-  --interval=20s --retries=5 \
-  CMD curl --fail localhost || exit 1
+# HEALTHCHECK \
+#   --interval=20s --retries=5 \
+#   CMD curl --fail localhost || exit 1
